//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_Client.IWS_Velib {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IWS_Velib.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCarto", ReplyAction="http://tempuri.org/IService1/GetCartoResponse")]
        string GetCarto();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCarto", ReplyAction="http://tempuri.org/IService1/GetCartoResponse")]
        System.Threading.Tasks.Task<string> GetCartoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetStationDetails", ReplyAction="http://tempuri.org/IService1/GetStationDetailsResponse")]
        string GetStationDetails(string town, int stationNb);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetStationDetails", ReplyAction="http://tempuri.org/IService1/GetStationDetailsResponse")]
        System.Threading.Tasks.Task<string> GetStationDetailsAsync(string town, int stationNb);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WS_Client.IWS_Velib.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WS_Client.IWS_Velib.IService1>, WS_Client.IWS_Velib.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetCarto() {
            return base.Channel.GetCarto();
        }
        
        public System.Threading.Tasks.Task<string> GetCartoAsync() {
            return base.Channel.GetCartoAsync();
        }
        
        public string GetStationDetails(string town, int stationNb) {
            return base.Channel.GetStationDetails(town, stationNb);
        }
        
        public System.Threading.Tasks.Task<string> GetStationDetailsAsync(string town, int stationNb) {
            return base.Channel.GetStationDetailsAsync(town, stationNb);
        }
    }
}
