//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_Client.IWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IWS.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LoadCities", ReplyAction="http://tempuri.org/IService1/LoadCitiesResponse")]
        string LoadCities();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LoadCities", ReplyAction="http://tempuri.org/IService1/LoadCitiesResponse")]
        System.Threading.Tasks.Task<string> LoadCitiesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetStationDetails", ReplyAction="http://tempuri.org/IService1/GetStationDetailsResponse")]
        string GetStationDetails(string contract_name);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IService1/GetStatistics", ReplyAction = "http://tempuri.org/IService1/GetStatistics")]
        string GetStatistics();

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetStationDetails", ReplyAction="http://tempuri.org/IService1/GetStationDetailsResponse")]
        System.Threading.Tasks.Task<string> GetStationDetailsAsync(string contract_name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WS_Client.IWS.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WS_Client.IWS.IService1>, WS_Client.IWS.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string LoadCities() {
            return base.Channel.LoadCities();
        }
        
        public System.Threading.Tasks.Task<string> LoadCitiesAsync() {
            return base.Channel.LoadCitiesAsync();
        }
        
        public string GetStationDetails(string contract_name) {
            return base.Channel.GetStationDetails(contract_name);
        }

        public string GetStatistics()
        {
            return base.Channel.GetStatistics();
        }
        
        public System.Threading.Tasks.Task<string> GetStationDetailsAsync(string contract_name) {
            return base.Channel.GetStationDetailsAsync(contract_name);
        }
    }
}
